site_name: Hudson Valley DockDogs Website Help
copyright: 2016 &copy; Brian J King unless otherwise noted. Made with <i class="fa fa-heart"></i> in Chicago.
site_description: Hudson Valley DockDogs Website Documentation
site_author: Brian J King
pages:
- Home: index.md 
theme: material
markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - pymdownx.tilde
    - markdown.extensions.smarty
    - pymdownx.smartsymbols

# Options
extra:
  version: '0.1.0'
  #logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'brianjking'
    twitter: 'brianjking'